### ISSUE TITLE
[SET UP] Scaffold App

### ISSUE THREAD

**Issue by MwinyiMoha** [BuildForSDG/asylum-fe#3]
**Scaffold App**

- Generate app using CLI tool

- Decide directory structure for code organization

**Comment by MwinyiMoha** [comment]
@MrObonye please note that the initial implementation was in React. If we end up switching to Angular, some of these files might need to be deleted. I think the `app.properties` file will remain but with a couple of change. Thanks

**Comment by thatguycodes** [comment]
@MwinyiMoha I have not use React as yet so I would rather prefer Angular. If you may ask the rest of the team mates that would be great.

**Comment by MwinyiMoha** [comment]
@MrObonye we can switch to Angular.

**Comment by thatguycodes** [comment]
@MwinyiMoha I will make that switch during the weekend. I want to thrown in a landing page so if you may  I just need brief description of what the solution is all about. You can just shoot me a DM on Slack
